from django.urls import path

from .views import (
    AppointmentCancelAPIView,
    AppointmentDetailAPIView,
    AppointmentListCreateAPIView,
    AppointmentRescheduleAPIView,
    AppointmentSummaryAPIView,
    BusinessHoursDetailAPIView,
    BusinessHoursListCreateAPIView,
    BusinessHoursSetDefaultAPIView,
    CompanyDetailsAPIView,
    DomainMappingDetailAPIView,
    DomainMappingListCreateAPIView,
    DomainMappingVerifyAPIView,
    FiscalYearAPIView,
    HierarchyPreferenceAPIView,
    HolidayDetailAPIView,
    HolidayListCreateAPIView,
    JobSheetDetailAPIView,
    JobSheetListCreateAPIView,
    ServiceDetailAPIView,
    ServiceListCreateAPIView,
    ServiceMemberDetailAPIView,
    ServiceMembersAPIView,
    ServicesEnableAPIView,
    ServicesSetupStatusAPIView,
    ServiceTeamMembersAPIView,
)

urlpatterns = [
    path("services/setup-status/", ServicesSetupStatusAPIView.as_view(), name="services-setup-status"),
    path("services/enable/", ServicesEnableAPIView.as_view(), name="services-enable"),
    path("services/team-members/", ServiceTeamMembersAPIView.as_view(), name="services-team-members"),
    path("services/business-hours/", BusinessHoursListCreateAPIView.as_view(), name="services-business-hours-list"),
    path("services/business-hours/<int:id>/", BusinessHoursDetailAPIView.as_view(), name="services-business-hours-detail"),
    path(
        "services/business-hours/<int:id>/set-default/",
        BusinessHoursSetDefaultAPIView.as_view(),
        name="services-business-hours-set-default",
    ),
    path("services/appointments/", AppointmentListCreateAPIView.as_view(), name="services-appointments-list"),
    path("services/appointments/summary/", AppointmentSummaryAPIView.as_view(), name="services-appointments-summary"),
    path("services/appointments/<int:id>/", AppointmentDetailAPIView.as_view(), name="services-appointments-detail"),
    path("services/appointments/<int:id>/cancel/", AppointmentCancelAPIView.as_view(), name="services-appointments-cancel"),
    path(
        "services/appointments/<int:id>/reschedule/",
        AppointmentRescheduleAPIView.as_view(),
        name="services-appointments-reschedule",
    ),
    path("services/job-sheets/", JobSheetListCreateAPIView.as_view(), name="services-job-sheets-list"),
    path("services/job-sheets/<int:id>/", JobSheetDetailAPIView.as_view(), name="services-job-sheets-detail"),
    path("services/<int:id>/members/", ServiceMembersAPIView.as_view(), name="services-members"),
    path(
        "services/<int:id>/members/<int:assignment_id>/",
        ServiceMemberDetailAPIView.as_view(),
        name="services-members-detail",
    ),
    path("services/<int:id>/", ServiceDetailAPIView.as_view(), name="services-detail"),
    path("services/", ServiceListCreateAPIView.as_view(), name="services-list"),
    path("settings/company-details/", CompanyDetailsAPIView.as_view(), name="services-company-details"),
    path("settings/domain-mapping/", DomainMappingListCreateAPIView.as_view(), name="services-domain-mapping-list"),
    path("settings/domain-mapping/<int:id>/", DomainMappingDetailAPIView.as_view(), name="services-domain-mapping-detail"),
    path("settings/domain-mapping/verify/", DomainMappingVerifyAPIView.as_view(), name="services-domain-mapping-verify"),
    path("settings/fiscal-year/", FiscalYearAPIView.as_view(), name="services-fiscal-year"),
    path("settings/holidays/", HolidayListCreateAPIView.as_view(), name="services-holidays-list"),
    path("settings/holidays/<int:id>/", HolidayDetailAPIView.as_view(), name="services-holidays-detail"),
    path("settings/hierarchy-preference/", HierarchyPreferenceAPIView.as_view(), name="services-hierarchy-preference"),
]
