# Generated by Django 5.2.12 on 2026-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_hr_role_and_department'),
    ]

    operations = []
