# Generated by Codex on 2026-03-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remove_organization_fk"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE authentication_user
                SET team = 'general'
                WHERE team IS NULL OR team = '';

                ALTER TABLE authentication_user
                ALTER COLUMN team SET DEFAULT 'general';
            """,
            reverse_sql="""
                ALTER TABLE authentication_user
                ALTER COLUMN team DROP DEFAULT;
            """,
        ),
    ]
