# Generated by Django 5.2.12 on 2026-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_assigned_report_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_report_keys',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Main Admin'), ('sub_admin', 'Sub Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('team_lead', 'Team Lead'), ('business_development', 'Business Development'), ('software_development', 'Software Development'), ('support_team', 'Support Team'), ('sales_manager', 'Sales Manager'), ('employee', 'Employee')], default='employee', max_length=30),
        ),
    ]
