# Generated by Django 5.2.12 on 2026-03-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_dealproduct'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dealproduct',
            new_name='deals_dealp_deal_id_ba6711_idx',
            old_name='deals_dealp_deal_id_034f9d_idx',
        ),
        migrations.RenameIndex(
            model_name='dealproduct',
            new_name='deals_dealp_product_ee8e60_idx',
            old_name='deals_dealp_product_d87c7e_idx',
        ),
        migrations.RenameIndex(
            model_name='dealproduct',
            new_name='deals_dealp_is_acti_573612_idx',
            old_name='deals_dealp_is_acti_89beba_idx',
        ),
    ]
