export const contactRelatedList = [
  "Notes",
  "Services",
  "Connected Records",
  "Attachments",
  "Cadences",
  "Deals",
  "Open Activities",
  "Closed Activities",
  "Invited Meetings",
  "Products",
  "Cases",
  "Solutions",
  "Quotes",
  "Sales Orders",
  "Purchase Orders",
  "Emails",
  "Social",
] as const;
