from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more"),
        ("contacts", "0002_alter_contact_options_remove_contact_owner_and_more"),
        ("deals", "0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more"),
        ("leads", "0005_alter_lead_lead_source_alter_lead_lead_status"),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BCCDropboxSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dropbox_email_address", models.EmailField(max_length=254, unique=True)),
                ("exclude_domains", models.JSONField(blank=True, default=list)),
                ("search_pattern_order", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="CustomEmailFieldPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailAuthenticationDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain_name", models.CharField(max_length=255, unique=True)),
                ("email_status", models.CharField(blank=True, max_length=100, null=True)),
                ("authentication_status", models.CharField(choices=[("available", "Available"), ("pending", "Pending"), ("authenticated", "Authenticated"), ("failed", "Failed")], default="available", max_length=20)),
                ("spf_status", models.CharField(blank=True, max_length=100, null=True)),
                ("dkim_status", models.CharField(blank=True, max_length=100, null=True)),
                ("dmarc_status", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailCredibilityMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("spam_complaints", models.PositiveIntegerField(default=0)),
                ("bounce_volume", models.PositiveIntegerField(default=0)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("delivered_count", models.PositiveIntegerField(default=0)),
                ("bounced_count", models.PositiveIntegerField(default=0)),
                ("report_period_start", models.DateField()),
                ("report_period_end", models.DateField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="EmailInsightSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("tracking_open", models.BooleanField(default=True)),
                ("tracking_click", models.BooleanField(default=True)),
                ("tracking_bounce", models.BooleanField(default=True)),
                ("workflow_trigger_enabled", models.BooleanField(default=False)),
                ("enabled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="email_insight_settings", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="EmailParserInbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parser_email_address", models.EmailField(max_length=254, unique=True)),
                ("parser_name", models.CharField(max_length=255)),
                ("mapping_config", models.JSONField(blank=True, default=dict)),
                ("create_record_type", models.CharField(choices=[("lead", "Lead"), ("contact", "Contact"), ("case", "Case"), ("custom", "Custom")], default="lead", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="EmailRelayServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("server_name", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("secure_connection", models.CharField(choices=[("ssl", "SSL"), ("tls", "TLS"), ("never", "Never")], default="tls", max_length=10)),
                ("daily_mail_limit", models.PositiveIntegerField(default=1000)),
                ("domain_name", models.CharField(max_length=255)),
                ("email_type", models.CharField(blank=True, max_length=100, null=True)),
                ("dkim_authentication_enabled", models.BooleanField(default=False)),
                ("bounce_management_enabled", models.BooleanField(default=False)),
                ("authentication_required", models.BooleanField(default=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailProviderIntegration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_type", models.CharField(choices=[("zoho_mail", "Zoho Mail"), ("gmail", "Gmail"), ("yahoo", "Yahoo Mail"), ("office365", "Office 365"), ("outlook", "Outlook"), ("other", "Other Mail")], max_length=30)),
                ("protocol_type", models.CharField(choices=[("imap_oauth", "IMAP OAuth"), ("imap", "IMAP"), ("smtp", "SMTP"), ("relay", "Relay")], max_length=20)),
                ("email_address", models.EmailField(max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=255, null=True)),
                ("reply_to_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_default_from", models.BooleanField(default=False)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("sales_inbox_enabled", models.BooleanField(default=False)),
                ("instant_notification_enabled", models.BooleanField(default=False)),
                ("crm_sync_enabled", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="email_provider_integrations", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="EmailSharingPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("configuration_type", models.CharField(max_length=100)),
                ("sharing_mode", models.CharField(choices=[("private", "Private"), ("public", "Public"), ("shared", "Shared"), ("role_based", "Role Based")], default="private", max_length=20)),
                ("shared_with_profiles", models.JSONField(blank=True, default=list)),
                ("excluded_domains", models.JSONField(blank=True, default=list)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email_sharing_permissions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationEmailAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("usage_scope", models.CharField(choices=[("standard", "Standard"), ("all_users", "All Users"), ("selected_profiles", "Selected Profiles")], default="standard", max_length=20)),
                ("confirmation_status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed")], default="pending", max_length=20)),
                ("authentication_status", models.CharField(choices=[("not_applicable", "Not Applicable"), ("pending", "Pending"), ("authenticated", "Authenticated"), ("failed", "Failed")], default="not_applicable", max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="organization_email_addresses", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SocialBrand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_name", models.CharField(max_length=255)),
                ("brand_description", models.TextField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="social_brands", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SocialPermissionSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("social_admin_role_name", models.CharField(max_length=255)),
                ("social_tab_profiles", models.JSONField(blank=True, default=list)),
                ("social_profiles", models.JSONField(blank=True, default=list)),
                ("private_handles_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UnsubscribeLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("location_type", models.CharField(choices=[("standard_page", "Standard Page"), ("custom_page", "Custom Page")], default="standard_page", max_length=20)),
                ("custom_url", models.URLField(blank=True, null=True)),
                ("action_type", models.CharField(choices=[("display_message", "Display Message"), ("redirect_url", "Redirect URL")], default="display_message", max_length=20)),
                ("redirect_url", models.URLField(blank=True, null=True)),
                ("display_message", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unsubscribe_links", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="VisitorTrackingPortal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("portal_name", models.CharField(max_length=255)),
                ("portal_url", models.URLField()),
                ("is_available", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visitor_tracking_portals", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(choices=[("facebook", "Facebook"), ("x", "X")], max_length=20)),
                ("account_name", models.CharField(blank=True, max_length=255, null=True)),
                ("handle", models.CharField(blank=True, max_length=255, null=True)),
                ("page_id", models.CharField(blank=True, max_length=255, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accounts", to="integrations.socialbrand")),
            ],
        ),
        migrations.CreateModel(
            name="SalesInboxSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("crm_context_enabled", models.BooleanField(default=True)),
                ("conversations_enabled", models.BooleanField(default=True)),
                ("timeline_enabled", models.BooleanField(default=True)),
                ("prioritized_columns_enabled", models.BooleanField(default=True)),
                ("provider_integration", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_inbox_settings", to="integrations.emailproviderintegration")),
            ],
        ),
        migrations.CreateModel(
            name="EmailComposeSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_font_family", models.CharField(default="Arial", max_length=120)),
                ("default_font_size", models.CharField(default="14px", max_length=20)),
                ("email_signature_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email_signature_html", models.TextField(blank=True, null=True)),
                ("is_plain_text", models.BooleanField(default=False)),
                ("default_from_integration", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_from_compose_settings", to="integrations.emailproviderintegration")),
                ("default_reply_to_integration", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_reply_to_compose_settings", to="integrations.emailproviderintegration")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_compose_settings", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="EmailSyncLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_type", models.CharField(choices=[("full_sync", "Full Sync"), ("incremental_sync", "Incremental Sync"), ("webhook_sync", "Webhook Sync"), ("parser_ingest", "Parser Ingest")], max_length=30)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("failed", "Failed")], default="pending", max_length=20)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("provider_integration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_logs", to="integrations.emailproviderintegration")),
            ],
        ),
        migrations.CreateModel(
            name="SocialLeadAutomationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(choices=[("facebook", "Facebook"), ("x", "X")], max_length=20)),
                ("trigger_type", models.CharField(choices=[("mention", "Mention"), ("comment", "Comment"), ("like", "Like"), ("retweet", "Retweet"), ("message", "Message")], max_length=20)),
                ("action_type", models.CharField(choices=[("create_lead", "Create Lead")], default="create_lead", max_length=20)),
                ("qualification_logic", models.JSONField(blank=True, default=dict)),
                ("assign_to_team", models.CharField(blank=True, max_length=255, null=True)),
                ("assign_to_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="social_lead_automation_rules", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SyncedEmailMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_message_id", models.CharField(max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("from_email", models.EmailField(max_length=254)),
                ("to_emails", models.JSONField(blank=True, default=list)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("bcc_emails", models.JSONField(blank=True, default=list)),
                ("body_text", models.TextField(blank=True, null=True)),
                ("body_html", models.TextField(blank=True, null=True)),
                ("direction", models.CharField(choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")], max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("sent", "Sent"), ("received", "Received"), ("failed", "Failed"), ("scheduled", "Scheduled")], max_length=20)),
                ("received_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("has_attachments", models.BooleanField(default=False)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="synced_email_messages", to="accounts.account")),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="synced_email_messages", to="contacts.contact")),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="synced_email_messages", to="deals.deal")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="synced_email_messages", to="leads.lead")),
                ("provider_integration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="synced_messages", to="integrations.emailproviderintegration")),
                ("support_case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="synced_email_messages", to="support.supportcase")),
            ],
        ),
        migrations.CreateModel(
            name="VisitorTrackingSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("push_new_visitors_as", models.CharField(choices=[("lead", "Lead"), ("contact", "Contact")], default="lead", max_length=20)),
                ("notify_when_visitor_online", models.BooleanField(default=False)),
                ("status_enabled", models.BooleanField(default=True)),
                ("department_name", models.CharField(blank=True, max_length=255, null=True)),
                ("app_name", models.CharField(max_length=255)),
                ("tracking_code", models.TextField()),
                ("chat_widget_enabled", models.BooleanField(default=True)),
                ("assign_lead_to_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visitor_tracking_settings", to=settings.AUTH_USER_MODEL)),
                ("portal", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="setting", to="integrations.visitortrackingportal")),
            ],
        ),
        migrations.CreateModel(
            name="VisitorLeadEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visitor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("visitor_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("page_history", models.JSONField(blank=True, default=list)),
                ("time_spent_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=100)),
                ("converted_to_lead", models.BooleanField(default=False)),
                ("linked_lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visitor_events", to="leads.lead")),
                ("portal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="integrations.visitortrackingportal")),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationLeadSourceEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(choices=[("email", "Email"), ("social", "Social"), ("website", "Website"), ("parser", "Parser"), ("bcc_dropbox", "BCC Dropbox"), ("salesiq", "SalesIQ")], max_length=20)),
                ("source_reference", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(max_length=100)),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="integration_source_events", to="contacts.contact")),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="integration_source_events", to="deals.deal")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="integration_source_events", to="leads.lead")),
            ],
        ),
        migrations.CreateModel(
            name="BCCDropboxVerifiedAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_address", models.EmailField(max_length=254)),
                ("verification_status", models.CharField(choices=[("pending", "Pending"), ("verified", "Verified")], default="pending", max_length=20)),
                ("verification_code", models.CharField(blank=True, max_length=32, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("bcc_setting", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="verified_addresses", to="integrations.bccdropboxsetting")),
            ],
        ),
    ]
