# Generated by Django 6.0.3 on 2026-03-17 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more'),
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('deals', '0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more'),
        ('integrations', '0001_initial'),
        ('leads', '0005_alter_lead_lead_source_alter_lead_lead_status'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bccdropboxsetting',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='bccdropboxverifiedaddress',
            options={'ordering': ['email_address']},
        ),
        migrations.AlterModelOptions(
            name='customemailfieldpreference',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='emailauthenticationdomain',
            options={'ordering': ['domain_name']},
        ),
        migrations.AlterModelOptions(
            name='emailcomposesetting',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='emailcredibilitymetric',
            options={'ordering': ['-report_period_end', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emailinsightsetting',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='emailparserinbox',
            options={'ordering': ['parser_name']},
        ),
        migrations.AlterModelOptions(
            name='emailproviderintegration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emailrelayserver',
            options={'ordering': ['server_name']},
        ),
        migrations.AlterModelOptions(
            name='emailsharingpermission',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='emailsynclog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='integrationleadsourceevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organizationemailaddress',
            options={'ordering': ['display_name', 'email_address']},
        ),
        migrations.AlterModelOptions(
            name='salesinboxsetting',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['platform', 'account_name']},
        ),
        migrations.AlterModelOptions(
            name='socialbrand',
            options={'ordering': ['brand_name']},
        ),
        migrations.AlterModelOptions(
            name='socialleadautomationrule',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='socialpermissionsetting',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='syncedemailmessage',
            options={'ordering': ['-received_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='unsubscribelink',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AlterModelOptions(
            name='visitorleadevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visitortrackingportal',
            options={'ordering': ['portal_name']},
        ),
        migrations.AlterModelOptions(
            name='visitortrackingsetting',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='emailauthenticationdomain',
            name='authentication_status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('authenticated', 'Authenticated'), ('failed', 'Failed')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailproviderintegration',
            name='email_address',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailproviderintegration',
            name='is_default_from',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='emailproviderintegration',
            name='provider_type',
            field=models.CharField(choices=[('zoho_mail', 'Zoho Mail'), ('gmail', 'Gmail'), ('yahoo', 'Yahoo Mail'), ('office365', 'Office 365'), ('outlook', 'Outlook'), ('other', 'Other Mail')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='emailsynclog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailsynclog',
            name='sync_type',
            field=models.CharField(choices=[('full_sync', 'Full Sync'), ('incremental_sync', 'Incremental Sync'), ('webhook_sync', 'Webhook Sync'), ('parser_ingest', 'Parser Ingest')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='integrationleadsourceevent',
            name='source_reference',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='integrationleadsourceevent',
            name='source_type',
            field=models.CharField(choices=[('email', 'Email'), ('social', 'Social'), ('website', 'Website'), ('parser', 'Parser'), ('bcc_dropbox', 'BCC Dropbox'), ('salesiq', 'SalesIQ')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationleadsourceevent',
            name='status',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationemailaddress',
            name='authentication_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('authenticated', 'Authenticated'), ('failed', 'Failed')], db_index=True, default='not_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationemailaddress',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='syncedemailmessage',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='syncedemailmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='syncedemailmessage',
            name='received_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='syncedemailmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='syncedemailmessage',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorleadevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorleadevent',
            name='visitor_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='emailproviderintegration',
            index=models.Index(fields=['provider_type', 'is_active'], name='integration_provide_042188_idx'),
        ),
        migrations.AddIndex(
            model_name='emailproviderintegration',
            index=models.Index(fields=['created_by', 'created_at'], name='integration_created_92e321_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationleadsourceevent',
            index=models.Index(fields=['source_type', 'created_at'], name='integration_source__22bf88_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationleadsourceevent',
            index=models.Index(fields=['status', 'created_at'], name='integration_status_c27a00_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorleadevent',
            index=models.Index(fields=['portal', 'created_at'], name='integration_portal__e33a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorleadevent',
            index=models.Index(fields=['event_type', 'created_at'], name='integration_event_t_8891eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='bccdropboxverifiedaddress',
            constraint=models.UniqueConstraint(fields=('bcc_setting', 'email_address'), name='integrations_bcc_verified_address_unique'),
        ),
        migrations.AddConstraint(
            model_name='emailproviderintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email_address',), name='integrations_active_provider_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='syncedemailmessage',
            constraint=models.UniqueConstraint(fields=('provider_integration', 'external_message_id'), name='integrations_synced_email_external_unique'),
        ),
    ]
