# Generated by Django 5.2.12 on 2026-03-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more'),
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('deals', '0005_dealproduct'),
        ('integrations', '0002_alter_bccdropboxsetting_options_and_more'),
        ('leads', '0005_alter_lead_lead_source_alter_lead_lead_status'),
        ('support', '0002_supportsolution_source_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X')], db_index=True, max_length=20)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('profile_handle', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('sender_phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('created_at_source', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at_source', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='integrationleadsourceevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_source_events', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='integrationleadsourceevent',
            name='support_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_source_events', to='support.supportcase'),
        ),
        migrations.AddField(
            model_name='visitorleadevent',
            name='identified_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitorleadevent',
            name='linked_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_events', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='visitorleadevent',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorleadevent',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorleadevent',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialleadautomationrule',
            name='action_type',
            field=models.CharField(choices=[('create_lead', 'Create Lead'), ('create_case', 'Create Case')], default='create_lead', max_length=20),
        ),
        migrations.AddIndex(
            model_name='visitorleadevent',
            index=models.Index(fields=['session_id', 'created_at'], name='integration_session_090d68_idx'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='integrations.socialbrand'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='integrations.socialaccount'),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='support_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages', to='support.supportcase'),
        ),
        migrations.AddConstraint(
            model_name='socialmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id__isnull', False)), fields=('platform', 'external_message_id'), name='integrations_social_external_unique'),
        ),
    ]
