# Generated by Codex on 2026-03-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more"),
        ("contacts", "0002_alter_contact_options_remove_contact_owner_and_more"),
        ("deals", "0005_dealproduct"),
        ("integrations", "0003_socialmessage_integrationleadsourceevent_account_and_more"),
        ("leads", "0005_alter_lead_lead_source_alter_lead_lead_status"),
        ("support", "0002_supportsolution_source_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailproviderintegration",
            name="imap_host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailproviderintegration",
            name="imap_port",
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name="emailproviderintegration",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailproviderintegration",
            name="smtp_host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailproviderintegration",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="emailproviderintegration",
            name="smtp_use_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailproviderintegration",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=120, null=True)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "email_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="integrations.syncedemailmessage",
                    ),
                ),
            ],
            options={"ordering": ["file_name", "created_at"]},
        ),
        migrations.CreateModel(
            name="EmailRecordLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_record_links",
                        to="accounts.account",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_record_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_record_links",
                        to="deals.deal",
                    ),
                ),
                (
                    "email_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_link",
                        to="integrations.syncedemailmessage",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_record_links",
                        to="leads.lead",
                    ),
                ),
                (
                    "support_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_record_links",
                        to="support.supportcase",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
