# Generated by Django 5.2.12 on 2026-03-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='activities__owner_i_e29227_idx',
            old_name='activities_ta_owner_created_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='activities__status_1fd7a1_idx',
            old_name='activities_ta_status_due_idx',
        ),
    ]
