# Generated by Django 5.2.12 on 2026-03-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_activities_ta_owner_created_idx_activities__owner_i_e29227_idx_and_more'),
    ]

    # `owner` is already created in 0006_task. Keeping this migration as a
    # no-op preserves migration history for databases that already recorded it
    # while preventing duplicate-column errors on fresh tenant migrations.
    operations = []
