# Generated by Django 5.2.12 on 2026-03-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_add_owner_to_task'),
    ]

    # `contact` and `account` are already created in 0006_task.
    operations = []
