# Generated by Django 5.2.12 on 2026-03-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_add_contact_account_to_task'),
    ]

    # `reminder` and `repeat` are already created in 0006_task.
    operations = []
