# Generated by Django 5.2.12 on 2026-03-17 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more'),
        ('activities', '0010_add_remaining_fields_to_task'),
        ('contacts', '0003_contact_city_contact_country_contact_description_and_more'),
        ('deals', '0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='contacts.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='deals.deal')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['organizer', 'start_date'], name='activities__organiz_eaf6b8_idx'), models.Index(fields=['status', 'start_date'], name='activities__status_26bca9_idx'), models.Index(fields=['contact', 'start_date'], name='activities__contact_dd0901_idx')],
            },
        ),
    ]
