# Generated by Django 5.2.12 on 2026-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_venue',
            field=models.CharField(choices=[('In-office', 'In-office'), ('Client location', 'Client location'), ('Online', 'Online')], default='In-office', max_length=32),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants_reminder',
            field=models.CharField(choices=[('None', 'None'), ('At time of meeting', 'At time of meeting'), ('5 minutes before', '5 minutes before'), ('10 minutes before', '10 minutes before'), ('15 minutes before', '15 minutes before'), ('30 minutes before', '30 minutes before'), ('1 hour before', '1 hour before'), ('2 hours before', '2 hours before')], default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='meeting',
            name='related_to',
            field=models.CharField(blank=True, default='None', max_length=32),
        ),
        migrations.AddField(
            model_name='meeting',
            name='repeat',
            field=models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='None', max_length=32),
        ),
    ]
