# Generated by Django 5.2.12 on 2026-03-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_add_meeting_extra_fields'),
        ('leads', '0006_alter_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='leads.lead'),
        ),
    ]
