# Generated by Django 5.2.12 on 2026-03-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0015_task_org_assignment"),
    ]

    operations = []
