# Generated by Django 5.2.12 on 2026-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_remove_organization_fk'),
    ]

    operations = []
