# Generated by Django 5.2.12 on 2026-03-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_meeting_meeting_link'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='call',
            new_name='activities__owner_i_3289d4_idx',
            old_name='activities_call_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='activities__call_st_23d3c3_idx',
            old_name='activities_call_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='activities__assigne_d9349c_idx',
            old_name='activities__assigne_created_idx',
        ),
    ]
