export const leadRelatedList = [
  "Notes",
  "Services",
  "Connected Records",
  "Cadences",
  "Attachments",
  "Products",
  "Open Activities",
  "Closed Activities",
  "Invited Meetings",
  "Emails",
  "Campaigns",
  "Social",
  "Links",
] as const;
