# Generated by Django 5.2.12 on 2026-03-16 10:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFiscalYearSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year_type', models.CharField(choices=[('standard', 'Standard Fiscal Year'), ('custom', 'Custom Fiscal Year')], default='standard', max_length=20)),
                ('starts_in_month', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHierarchyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preference', models.CharField(default='role_based', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_services_enabled', models.BooleanField(default=False)),
                ('default_timezone', models.CharField(default='Asia/Calcutta', max_length=100)),
                ('hide_promo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('monday_enabled', models.BooleanField(default=False)),
                ('monday_start', models.TimeField(blank=True, null=True)),
                ('monday_end', models.TimeField(blank=True, null=True)),
                ('tuesday_enabled', models.BooleanField(default=False)),
                ('tuesday_start', models.TimeField(blank=True, null=True)),
                ('tuesday_end', models.TimeField(blank=True, null=True)),
                ('wednesday_enabled', models.BooleanField(default=False)),
                ('wednesday_start', models.TimeField(blank=True, null=True)),
                ('wednesday_end', models.TimeField(blank=True, null=True)),
                ('thursday_enabled', models.BooleanField(default=False)),
                ('thursday_start', models.TimeField(blank=True, null=True)),
                ('thursday_end', models.TimeField(blank=True, null=True)),
                ('friday_enabled', models.BooleanField(default=False)),
                ('friday_start', models.TimeField(blank=True, null=True)),
                ('friday_end', models.TimeField(blank=True, null=True)),
                ('saturday_enabled', models.BooleanField(default=False)),
                ('saturday_start', models.TimeField(blank=True, null=True)),
                ('saturday_end', models.TimeField(blank=True, null=True)),
                ('sunday_enabled', models.BooleanField(default=False)),
                ('sunday_start', models.TimeField(blank=True, null=True)),
                ('sunday_end', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CRMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_code', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('service_name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('location_type', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('in_store', 'In Store'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20)),
                ('available_days_mode', models.CharField(choices=[('business_hours', 'Business Hours'), ('custom', 'Custom'), ('all_days', 'All Days')], default='business_hours', max_length=30)),
                ('available_time_mode', models.CharField(choices=[('business_hours', 'Business Hours'), ('custom', 'Custom'), ('all_days', 'All Days')], default='business_hours', max_length=30)),
                ('business_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.businesshours')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services_catalog_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_services_catalog_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('appointment_for_type', models.CharField(choices=[('contact', 'Contact'), ('account', 'Account'), ('lead', 'Lead'), ('deal', 'Deal'), ('product', 'Product'), ('other', 'Other')], default='other', max_length=20)),
                ('appointment_for_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_start_time', models.TimeField()),
                ('appointment_end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.crmservice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_service_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDomainMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('crm', 'CRM'), ('sandbox', 'Sandbox'), ('portals', 'Portals')], max_length=20)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('cname_target', models.CharField(default='crm.cs.zohohost.in', max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_type'], name='services_se_account_cf89cd_idx'), models.Index(fields=['verification_status'], name='services_se_verific_70e3f5_idx'), models.Index(fields=['is_active'], name='services_se_is_acti_4cc0e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['date'], name='services_se_date_26abdc_idx'), models.Index(fields=['is_active'], name='services_se_is_acti_3b1797_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceJobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_sheets', to='services.serviceappointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_job_sheets', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sheets', to='services.crmservice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_service_job_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceJobSheetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(default='text', max_length=50)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('job_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='services.servicejobsheet')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMemberAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='services.crmservice')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['name'], name='services_bu_name_fa4826_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['is_default'], name='services_bu_is_defa_78806a_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['is_active'], name='services_bu_is_acti_bba2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='crmservice',
            index=models.Index(fields=['service_code'], name='services_cr_service_f5b087_idx'),
        ),
        migrations.AddIndex(
            model_name='crmservice',
            index=models.Index(fields=['service_name'], name='services_cr_service_db6405_idx'),
        ),
        migrations.AddIndex(
            model_name='crmservice',
            index=models.Index(fields=['status'], name='services_cr_status_ff27ab_idx'),
        ),
        migrations.AddIndex(
            model_name='crmservice',
            index=models.Index(fields=['business_hours'], name='services_cr_busines_87b1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='crmservice',
            index=models.Index(fields=['is_active'], name='services_cr_is_acti_b771fa_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['appointment_number'], name='services_se_appoint_cc361d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['appointment_date'], name='services_se_appoint_de41d0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['status'], name='services_se_status_a40207_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['assigned_member'], name='services_se_assigne_3c07de_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['appointment_for_type', 'appointment_for_id'], name='services_se_appoint_57b6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_86fb93_idx'),
        ),
        migrations.AddIndex(
            model_name='servicejobsheet',
            index=models.Index(fields=['service'], name='services_se_service_5e3924_idx'),
        ),
        migrations.AddIndex(
            model_name='servicejobsheet',
            index=models.Index(fields=['appointment'], name='services_se_appoint_7a25f0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicejobsheet',
            index=models.Index(fields=['status'], name='services_se_status_10a95f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicejobsheet',
            index=models.Index(fields=['customer_type', 'customer_id'], name='services_se_custome_44e4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicejobsheet',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_c7c801_idx'),
        ),
        migrations.AddIndex(
            model_name='servicejobsheetfield',
            index=models.Index(fields=['job_sheet', 'field_name'], name='services_se_job_she_20a976_idx'),
        ),
        migrations.AddIndex(
            model_name='servicememberassignment',
            index=models.Index(fields=['service', 'member'], name='services_se_service_8ce825_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicememberassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('service', 'member'), name='services_active_member_assignment_unique'),
        ),
    ]
