# Generated by Django 5.2.12 on 2026-03-19 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_inventory_q_price_b_0f3fa5_idx_inventory_q_price_b_1652b2_idx'),
        ('services', '0003_alter_crmservice_location_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='completion_proof_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='coverage_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Verification')], db_index=True, default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='coverage_type',
            field=models.CharField(choices=[('none', 'None'), ('warranty', 'Warranty'), ('amc', 'AMC'), ('paid', 'Paid')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='customer_asset_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to='inventory.invoice'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='product_serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointments', to='inventory.salesorder'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['product'], name='services_se_product_3f7b63_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['sales_order'], name='services_se_sales_o_45b204_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['invoice'], name='services_se_invoice_9fdd81_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceappointment',
            index=models.Index(fields=['coverage_type', 'coverage_status'], name='services_se_coverag_3c530b_idx'),
        ),
    ]
