# Generated by Django 5.2.12 on 2026-03-22 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_crmservice_delivery_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='completion_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='services/appointments/'),
        ),
        migrations.AddIndex(
            model_name='crmservice',
            index=models.Index(fields=['delivery_team'], name='services_cr_deliver_bf378a_idx'),
        ),
    ]
