# Generated by Django 5.2.12 on 2026-03-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0007_add_tags_to_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_converted', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaigns.campaign')),
                ('converted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_submissions', to='leads.lead')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['campaign', 'submitted_at'], name='campaigns_c_campaig_b06abc_idx'), models.Index(fields=['email'], name='campaigns_c_email_a46744_idx')],
            },
        ),
    ]
