import { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import DashboardLayout from "../../components/layout/DashboardLayout";
import { createJobSheet, getJobSheet, listAppointments, listServices, updateJobSheet } from "../api";
import { buildEmptyJobSheetField } from "../utils";
import { jobSheetStatusOptions } from "../config";
import type { AppointmentRecord, JobSheetFormData, ServiceRecord } from "../types";

const inputClass = "h-[38px] w-full rounded-md border border-slate-300 px-3 text-sm outline-none focus:border-green-500";
const textareaClass = "min-h-[96px] w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-green-500";

const emptyForm: JobSheetFormData = {
  appointmentId: "",
  serviceId: "",
  customerType: "",
  customerId: "",
  title: "",
  status: "draft",
  fields: [buildEmptyJobSheetField()],
};

export default function JobSheetFormPage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const [searchParams] = useSearchParams();
  const isEdit = Boolean(id);
  const [form, setForm] = useState<JobSheetFormData>({ ...emptyForm, appointmentId: searchParams.get("appointment") || "", serviceId: searchParams.get("service") || "" });
  const [appointments, setAppointments] = useState<AppointmentRecord[]>([]);
  const [services, setServices] = useState<ServiceRecord[]>([]);
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(Boolean(id));
  const [error, setError] = useState<string | null>(null);
  const filteredAppointments = form.serviceId
    ? appointments.filter((item) => item.serviceId === form.serviceId)
    : appointments;
  const selectedAppointment = appointments.find((item) => item.id === form.appointmentId);
  const selectedService = services.find((item) => item.id === form.serviceId);

  useEffect(() => {
    const load = async () => {
      try {
        const [appointmentRows, serviceRows] = await Promise.all([listAppointments(), listServices()]);
        setAppointments(appointmentRows);
        setServices(serviceRows);
        if (id) {
          const detail = await getJobSheet(id);
          setForm({
            appointmentId: detail.appointmentId,
            serviceId: detail.serviceId,
            customerType: detail.customerType,
            customerId: detail.customerId,
            title: detail.title,
            status: detail.status,
            fields: detail.fields.length ? detail.fields : [buildEmptyJobSheetField()],
          });
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unable to load job sheet form.");
      } finally {
        setLoading(false);
      }
    };
    void load();
  }, [id]);

  useEffect(() => {
    if (!form.appointmentId) return;
    if (selectedAppointment && form.serviceId && selectedAppointment.serviceId !== form.serviceId) {
      setForm((prev) => ({ ...prev, appointmentId: "" }));
    }
  }, [selectedAppointment, form.serviceId]);

  useEffect(() => {
    if (!selectedAppointment || isEdit) return;
    const generatedTitle = [
      selectedAppointment.appointmentNumber,
      selectedService?.serviceName || selectedAppointment.serviceName,
      selectedAppointment.appointmentForDisplay,
    ]
      .filter(Boolean)
      .join(" - ");

    setForm((prev) => {
      const looksAutoGenerated =
        !prev.title.trim() ||
        prev.title === prev.appointmentId ||
        prev.title === (selectedService?.serviceName || selectedAppointment.serviceName) ||
        prev.title === selectedAppointment.appointmentForDisplay ||
        prev.title === "PD";

      if (!looksAutoGenerated) return prev;
      return { ...prev, title: generatedTitle };
    });
  }, [isEdit, selectedAppointment, selectedService]);

  const handleSubmit = async () => {
    if (!form.serviceId) return setError("Service is required.");
    if (!form.title.trim()) return setError("Title is required.");
    if (form.fields.some((field) => !field.fieldName.trim() || !field.fieldLabel.trim())) return setError("Each job-sheet field needs a name and label.");
    try {
      setSaving(true);
      setError(null);
      const record = isEdit && id ? await updateJobSheet(id, form) : await createJobSheet(form);
      navigate(`/services/job-sheets/${record.id}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to save job sheet.");
    } finally {
      setSaving(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-4">
        <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-5 py-4">
          <div>
            <h1 className="text-lg font-semibold text-slate-900">{isEdit ? "Edit Job Sheet" : "Create Job Sheet"}</h1>
            <p className="text-sm text-slate-500">Capture custom service execution details in a structured job sheet.</p>
          </div>
          <div className="flex gap-2">
            <button type="button" onClick={() => navigate("/services/catalog")} className="rounded-md border border-slate-300 px-4 py-2 text-sm text-slate-700">Cancel</button>
            <button type="button" disabled={saving} onClick={() => void handleSubmit()} className="rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white">{saving ? "Saving..." : "Save"}</button>
          </div>
        </div>

        {loading ? <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading job sheet...</div> : null}
        {error ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-600">{error}</div> : null}

        {!loading ? (
          <div className="space-y-4">
            <div className="rounded-xl border border-slate-200 bg-white p-5">
              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-slate-700">Title</label>
                  <input className={inputClass} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
                </div>
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-slate-700">Status</label>
                  <select className={inputClass} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>
                    {jobSheetStatusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
                  </select>
                </div>
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-slate-700">Service</label>
                  <select
                    className={inputClass}
                    value={form.serviceId}
                    onChange={(e) =>
                      setForm((prev) => {
                        const nextServiceId = e.target.value;
                        const currentAppointment = appointments.find((item) => item.id === prev.appointmentId);
                        return {
                          ...prev,
                          serviceId: nextServiceId,
                          appointmentId:
                            currentAppointment && currentAppointment.serviceId === nextServiceId
                              ? prev.appointmentId
                              : "",
                        };
                      })
                    }
                  >
                    <option value="">Select service</option>
                    {services.map((item) => <option key={item.id} value={item.id}>{item.serviceName}</option>)}
                  </select>
                </div>
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-slate-700">Appointment</label>
                  <select className={inputClass} value={form.appointmentId} onChange={(e) => setForm({ ...form, appointmentId: e.target.value })}>
                    <option value="">Select appointment</option>
                    {filteredAppointments.map((item) => <option key={item.id} value={item.id}>{item.appointmentNumber} • {item.appointmentForDisplay}</option>)}
                  </select>
                </div>
              </div>
              {selectedAppointment ? (
                <div className="mt-4 grid gap-3 md:grid-cols-3">
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                    <div className="text-xs uppercase tracking-wide text-slate-500">Customer Context</div>
                    <div className="mt-1 text-sm font-medium text-slate-800">{selectedAppointment.appointmentForDisplay || "-"}</div>
                  </div>
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                    <div className="text-xs uppercase tracking-wide text-slate-500">Sales Order</div>
                    <div className="mt-1 text-sm font-medium text-slate-800">
                      {selectedAppointment.salesOrderSubject || selectedAppointment.salesOrderId || "-"}
                    </div>
                  </div>
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                    <div className="text-xs uppercase tracking-wide text-slate-500">Invoice</div>
                    <div className="mt-1 text-sm font-medium text-slate-800">
                      {selectedAppointment.invoiceSubject || selectedAppointment.invoiceId || "-"}
                    </div>
                  </div>
                </div>
              ) : null}
            </div>

            <div className="rounded-xl border border-slate-200 bg-white p-5">
              <div className="mb-4 flex items-center justify-between">
                <h2 className="text-sm font-semibold text-slate-900">Job Sheet Fields</h2>
                <button type="button" onClick={() => setForm((prev) => ({ ...prev, fields: [...prev.fields, buildEmptyJobSheetField()] }))} className="rounded-md border border-slate-300 px-3 py-2 text-sm text-slate-700">Add Field</button>
              </div>
              <div className="space-y-4">
                {form.fields.map((field, index) => (
                  <div key={field.clientKey || field.id || `job-field-${index}`} className="grid gap-3 rounded-lg border border-slate-200 p-4 md:grid-cols-4">
                    <div>
                      <label className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">Field Name</label>
                      <input className={inputClass} placeholder="internal_key" value={field.fieldName} onChange={(e) => setForm((prev) => ({ ...prev, fields: prev.fields.map((item, itemIndex) => itemIndex === index ? { ...item, fieldName: e.target.value } : item) }))} />
                    </div>
                    <div>
                      <label className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">Field Label</label>
                      <input className={inputClass} placeholder="Display label" value={field.fieldLabel} onChange={(e) => setForm((prev) => ({ ...prev, fields: prev.fields.map((item, itemIndex) => itemIndex === index ? { ...item, fieldLabel: e.target.value } : item) }))} />
                    </div>
                    <div>
                      <label className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">Field Type</label>
                      <select className={inputClass} value={field.fieldType} onChange={(e) => setForm((prev) => ({ ...prev, fields: prev.fields.map((item, itemIndex) => itemIndex === index ? { ...item, fieldType: e.target.value as any } : item) }))}>
                      <option value="text">Text</option>
                      <option value="date">Date</option>
                      <option value="textarea">Textarea</option>
                      </select>
                    </div>
                    <button type="button" onClick={() => setForm((prev) => ({ ...prev, fields: prev.fields.length === 1 ? [buildEmptyJobSheetField()] : prev.fields.filter((_, itemIndex) => itemIndex !== index) }))} className="rounded-md border border-rose-300 px-3 py-2 text-sm text-rose-600">Remove</button>
                    <div className="md:col-span-4">
                      <label className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">Field Value</label>
                      {field.fieldType === "textarea" ? (
                        <textarea className={textareaClass} placeholder="Value" value={field.fieldValue} onChange={(e) => setForm((prev) => ({ ...prev, fields: prev.fields.map((item, itemIndex) => itemIndex === index ? { ...item, fieldValue: e.target.value } : item) }))} />
                      ) : (
                        <input type={field.fieldType === "date" ? "date" : "text"} className={inputClass} placeholder="Value" value={field.fieldValue} onChange={(e) => setForm((prev) => ({ ...prev, fields: prev.fields.map((item, itemIndex) => itemIndex === index ? { ...item, fieldValue: e.target.value } : item) }))} />
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </DashboardLayout>
  );
}
