# Generated manually for inventory domain integration

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more"),
        ("contacts", "0002_alter_contact_options_remove_contact_owner_and_more"),
        ("deals", "0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more"),
        ("leads", "0005_alter_lead_lead_source_alter_lead_lead_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_street", models.CharField(blank=True, max_length=255, null=True)),
                ("billing_city", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_state", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_country", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("shipping_street", models.CharField(blank=True, max_length=255, null=True)),
                ("shipping_city", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_state", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_country", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("vendor_name", models.CharField(db_index=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("vendor_owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_vendors", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                ("product_code", models.CharField(db_index=True, max_length=120, unique=True)),
                ("manufacturer", models.CharField(blank=True, max_length=255, null=True)),
                ("product_category", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("commission_rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("quantity_in_demand", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("usage_unit", models.CharField(blank=True, max_length=100, null=True)),
                ("support_start_date", models.DateField(blank=True, null=True)),
                ("support_expiry_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_product_owner", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="products", to="inventory.vendor")),
            ],
        ),
        migrations.CreateModel(
            name="PriceBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("pricing_model", models.CharField(choices=[("fixed", "Fixed"), ("range", "Range"), ("cpq", "CPQ")], default="fixed", max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_pricebook_owner", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PriceBookRange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_range", models.PositiveIntegerField()),
                ("to_range", models.PositiveIntegerField()),
                ("discount_percentage", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7)),
                ("price_book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ranges", to="inventory.pricebook")),
            ],
        ),
        migrations.CreateModel(
            name="PriceBookProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("list_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("active", models.BooleanField(default=True)),
                ("price_book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_links", to="inventory.pricebook")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="price_book_links", to="inventory.product")),
            ],
        ),
        migrations.AddField(
            model_name="pricebook",
            name="products",
            field=models.ManyToManyField(blank=True, related_name="price_books", through="inventory.PriceBookProduct", to="inventory.product"),
        ),
        migrations.CreateModel(
            name="ProductConfigurator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("target_module", models.CharField(db_index=True, max_length=100)),
                ("layout", models.CharField(blank=True, max_length=100, null=True)),
                ("subform", models.CharField(blank=True, max_length=100, null=True)),
                ("lookup_field", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguratorRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("action_type", models.CharField(choices=[("mandatory_product", "Mandatory Product"), ("suggest_product", "Suggest Product"), ("field_update", "Field Update")], db_index=True, max_length=50)),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                ("field_value", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("configurator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="inventory.productconfigurator")),
                ("target_product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="configurator_rules", to="inventory.product")),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_street", models.CharField(blank=True, max_length=255, null=True)),
                ("billing_city", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_state", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_country", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("shipping_street", models.CharField(blank=True, max_length=255, null=True)),
                ("shipping_city", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_state", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_country", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("adjustment", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("grand_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(db_index=True, max_length=255)),
                ("quote_stage", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                ("carrier", models.CharField(blank=True, max_length=120, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_quotes", to="accounts.account")),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_quotes", to="contacts.contact")),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_quotes", to="deals.deal")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_quote_owner", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_street", models.CharField(blank=True, max_length=255, null=True)),
                ("billing_city", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_state", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_country", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("shipping_street", models.CharField(blank=True, max_length=255, null=True)),
                ("shipping_city", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_state", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_country", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("adjustment", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("grand_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(db_index=True, max_length=255)),
                ("customer_no", models.CharField(blank=True, max_length=100, null=True)),
                ("pending", models.BooleanField(default=False)),
                ("carrier", models.CharField(blank=True, max_length=120, null=True)),
                ("sales_commission", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("excise_duty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("status", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_sales_orders", to="accounts.account")),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_sales_orders", to="contacts.contact")),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_sales_orders", to="deals.deal")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_salesorder_owner", to=settings.AUTH_USER_MODEL)),
                ("quote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_orders", to="inventory.quote")),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_street", models.CharField(blank=True, max_length=255, null=True)),
                ("billing_city", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_state", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_country", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("shipping_street", models.CharField(blank=True, max_length=255, null=True)),
                ("shipping_city", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_state", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_country", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("adjustment", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("grand_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(db_index=True, max_length=255)),
                ("requisition_number", models.CharField(blank=True, max_length=120, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("excise_duty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("status", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("po_number", models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=120, null=True)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=120, null=True)),
                ("sales_commission", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_purchase_orders", to="contacts.contact")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_purchaseorder_owner", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_orders", to="inventory.vendor")),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_street", models.CharField(blank=True, max_length=255, null=True)),
                ("billing_city", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_state", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_country", models.CharField(blank=True, max_length=100, null=True)),
                ("billing_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("shipping_street", models.CharField(blank=True, max_length=255, null=True)),
                ("shipping_city", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_state", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_country", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping_zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("adjustment", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("grand_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(db_index=True, max_length=255)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("sales_commission", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("excise_duty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("status", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_invoices", to="accounts.account")),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_invoices", to="contacts.contact")),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_invoices", to="deals.deal")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_invoice_owner", to=settings.AUTH_USER_MODEL)),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoices", to="inventory.purchaseorder")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoices", to="inventory.salesorder")),
            ],
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("list_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("row_description", models.TextField(blank=True, null=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="quote_items", to="inventory.product")),
                ("quote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="inventory.quote")),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("list_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("row_description", models.TextField(blank=True, null=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sales_order_items", to="inventory.product")),
                ("sales_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="inventory.salesorder")),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("list_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("row_description", models.TextField(blank=True, null=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_items", to="inventory.product")),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="inventory.purchaseorder")),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("list_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("row_description", models.TextField(blank=True, null=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="inventory.invoice")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoice_items", to="inventory.product")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField()),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_notes", to=settings.AUTH_USER_MODEL)),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="inventory.invoice")),
                ("price_book", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="inventory.pricebook")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="inventory.product")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="inventory.purchaseorder")),
                ("quote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="inventory.quote")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="inventory.salesorder")),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="inventory.vendor")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="inventory.invoice")),
                ("price_book", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="inventory.pricebook")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="inventory.product")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="inventory.purchaseorder")),
                ("quote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="inventory.quote")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="inventory.salesorder")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_activities", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="inventory.vendor")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="inventory/")),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="inventory.invoice")),
                ("price_book", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="inventory.pricebook")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="inventory.product")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="inventory.purchaseorder")),
                ("quote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="inventory.quote")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="inventory.salesorder")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_attachments", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="inventory.vendor")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryEmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="inventory.invoice")),
                ("price_book", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="inventory.pricebook")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="inventory.product")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="inventory.purchaseorder")),
                ("quote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="inventory.quote")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="inventory.salesorder")),
                ("sent_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_email_logs", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="inventory.vendor")),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLinkedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relationship_label", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inventory_links", to="accounts.account")),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inventory_links", to="contacts.contact")),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inventory_links", to="deals.deal")),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="linked_records", to="inventory.invoice")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inventory_links", to="leads.lead")),
                ("price_book", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="linked_records", to="inventory.pricebook")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="linked_records", to="inventory.product")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="linked_records", to="inventory.purchaseorder")),
                ("quote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="linked_records", to="inventory.quote")),
                ("sales_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="linked_records", to="inventory.salesorder")),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="linked_records", to="inventory.vendor")),
            ],
        ),
        migrations.AddConstraint(
            model_name="pricebookproduct",
            constraint=models.UniqueConstraint(fields=("price_book", "product"), name="inventory_price_book_product_unique"),
        ),
    ]
