# Generated by Django 6.0.3 on 2026-03-16 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more'),
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('deals', '0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuratorrule',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pricebook',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pricebookrange',
            options={'ordering': ['from_range', 'id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productconfigurator',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subject'], name='inventory_i_subject_56dbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='inventory_i_status_91e14d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['account'], name='inventory_i_account_d2f3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contact'], name='inventory_i_contact_8bb2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['deal'], name='inventory_i_deal_id_a0ea32_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sales_order'], name='inventory_i_sales_o_21b3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['purchase_order'], name='inventory_i_purchas_c3ea0e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner'], name='inventory_i_owner_i_a2f4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebook',
            index=models.Index(fields=['name'], name='inventory_p_name_a8645d_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebook',
            index=models.Index(fields=['owner'], name='inventory_p_owner_i_06b1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebook',
            index=models.Index(fields=['active'], name='inventory_p_active_bd0609_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebookrange',
            index=models.Index(fields=['price_book', 'from_range', 'to_range'], name='inventory_p_price_b_9fdd15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='inventory_p_product_3437c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='inventory_p_product_ee59bd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_category'], name='inventory_p_product_e050fa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='inventory_p_vendor__7ee356_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner'], name='inventory_p_owner_i_cbbddf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx'),
        ),
        migrations.AddIndex(
            model_name='productconfigurator',
            index=models.Index(fields=['name'], name='inventory_p_name_a45e85_idx'),
        ),
        migrations.AddIndex(
            model_name='productconfigurator',
            index=models.Index(fields=['target_module'], name='inventory_p_target__772592_idx'),
        ),
        migrations.AddIndex(
            model_name='productconfigurator',
            index=models.Index(fields=['active'], name='inventory_p_active_6474d9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['subject'], name='inventory_p_subject_d1ee8f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='inventory_p_status_43427b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor'], name='inventory_p_vendor__712bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['contact'], name='inventory_p_contact_ea1e08_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='inventory_p_po_numb_319f55_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['owner'], name='inventory_p_owner_i_5ba700_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['subject'], name='inventory_q_subject_9970bc_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_stage'], name='inventory_q_quote_s_89af37_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['account'], name='inventory_q_account_6c9d82_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['contact'], name='inventory_q_contact_2c230f_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['deal'], name='inventory_q_deal_id_574adc_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['owner'], name='inventory_q_owner_i_c986d8_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['subject'], name='inventory_s_subject_5484ad_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='inventory_s_status_7af73e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['account'], name='inventory_s_account_b1c328_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['contact'], name='inventory_s_contact_16d63f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['deal'], name='inventory_s_deal_id_c7673b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['quote'], name='inventory_s_quote_i_80b754_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['owner'], name='inventory_s_owner_i_daa1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_name'], name='inventory_v_vendor__20dcaa_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_owner'], name='inventory_v_vendor__0ce7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category'], name='inventory_v_categor_20d8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='inventory_v_is_acti_618271_idx'),
        ),
    ]
