# Generated by Django 5.2.12 on 2026-03-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_quote_price_book'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quote',
            new_name='inventory_q_price_b_1652b2_idx',
            old_name='inventory_q_price_b_0f3fa5_idx',
        ),
    ]
