# Generated by Django 5.2.12 on 2026-03-31 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_software_product_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='inventory_p_product_3c97c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['billing_cycle'], name='inventory_p_billing_271900_idx'),
        ),
    ]
