# Generated by Django 5.2.12 on 2026-03-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_related_638384_idx',
            old_name='docs_module_related_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_is_acti_ba34b3_idx',
            old_name='docs_active_created_idx',
        ),
    ]
