# Generated by Django 5.2.12 on 2026-03-16 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more'),
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('deals', '0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more'),
        ('inventory', '0002_alter_configuratorrule_options_alter_invoice_options_and_more'),
        ('leads', '0005_alter_lead_lead_source_alter_lead_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('case_origin', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('case_reason', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('internal_comments', models.TextField(blank=True, null=True)),
                ('solution_text', models.TextField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_comments', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_cases', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='deals.deal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_support_cases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='inventory.product')),
                ('related_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_support_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_type', models.CharField(choices=[('case', 'Case'), ('solution', 'Solution')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to='support/imports/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('operation', models.CharField(blank=True, max_length=30, null=True)),
                ('duplicate_check_field', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('default_values', models.JSONField(blank=True, default=dict)),
                ('automation_enabled', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solution_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('solution_title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('no_of_comments', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_solutions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_support_solutions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_solutions', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_support_solutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='support.supportcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_notes', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='support.supportsolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportLinkedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_label', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_links', to='accounts.account')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_records', to='support.supportcase')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_links', to='contacts.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_links', to='deals.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_links', to='leads.lead')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_links', to='inventory.product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_links', to='inventory.vendor')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_records', to='support.supportsolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='support.supportcase')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_email_logs', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='support.supportsolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.supportcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_comments', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.supportsolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='support/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=120, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_attachments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportcase')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportsolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_activities', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='support.supportcase')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='support.supportsolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_type', models.CharField(choices=[('case', 'Case'), ('solution', 'Solution')], db_index=True, max_length=20)),
                ('record_id', models.PositiveBigIntegerField(db_index=True)),
                ('action_type', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['case_number'], name='support_sup_case_nu_172974_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['subject'], name='support_sup_subject_e73d82_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['status'], name='support_sup_status_a2e022_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['priority'], name='support_sup_priorit_853d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['case_origin'], name='support_sup_case_or_cb8258_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['company'], name='support_sup_company_40048c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['country'], name='support_sup_country_e8ed87_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['owner'], name='support_sup_owner_i_65b39a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['account'], name='support_sup_account_20abeb_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['related_contact'], name='support_sup_related_1e4437_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['deal'], name='support_sup_deal_id_1282bc_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['product'], name='support_sup_product_47859b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['last_activity_at'], name='support_sup_last_ac_0ab678_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['is_active'], name='support_sup_is_acti_b926a9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportimportjob',
            index=models.Index(fields=['module_type', 'status', 'created_at'], name='support_sup_module__15adb8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsolution',
            index=models.Index(fields=['solution_number'], name='support_sup_solutio_69d39e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsolution',
            index=models.Index(fields=['solution_title'], name='support_sup_solutio_aea201_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsolution',
            index=models.Index(fields=['status'], name='support_sup_status_391ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsolution',
            index=models.Index(fields=['owner'], name='support_sup_owner_i_e3e589_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsolution',
            index=models.Index(fields=['product'], name='support_sup_product_7fccb6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsolution',
            index=models.Index(fields=['last_activity_at'], name='support_sup_last_ac_e00758_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsolution',
            index=models.Index(fields=['is_active'], name='support_sup_is_acti_445587_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnote',
            index=models.Index(fields=['case', 'created_at'], name='support_sup_case_id_8b429d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnote',
            index=models.Index(fields=['solution', 'created_at'], name='support_sup_solutio_29d428_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcomment',
            index=models.Index(fields=['case', 'created_at'], name='support_sup_case_id_d0fe5e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcomment',
            index=models.Index(fields=['solution', 'created_at'], name='support_sup_solutio_d064e4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportattachment',
            index=models.Index(fields=['case', 'created_at'], name='support_sup_case_id_8aeb27_idx'),
        ),
        migrations.AddIndex(
            model_name='supportattachment',
            index=models.Index(fields=['solution', 'created_at'], name='support_sup_solutio_a1db49_idx'),
        ),
        migrations.AddIndex(
            model_name='supportactivity',
            index=models.Index(fields=['case', 'is_closed', 'created_at'], name='support_sup_case_id_a2beaf_idx'),
        ),
        migrations.AddIndex(
            model_name='supportactivity',
            index=models.Index(fields=['solution', 'is_closed', 'created_at'], name='support_sup_solutio_0dac13_idx'),
        ),
        migrations.AddIndex(
            model_name='supporttimelineentry',
            index=models.Index(fields=['module_type', 'record_id', 'created_at'], name='support_sup_module__9ccccc_idx'),
        ),
        migrations.AddIndex(
            model_name='supporttimelineentry',
            index=models.Index(fields=['action_type'], name='support_sup_action__3f2108_idx'),
        ),
    ]
