# Generated by Django 5.2.12 on 2026-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportsolution_source_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsolution',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
