# Generated by Django 5.2.12 on 2026-04-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_supportcase_lead'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportcase',
            new_name='support_sup_lead_id_b68000_idx',
            old_name='supportcase_lead_idx',
        ),
    ]
