from __future__ import annotations

REPORT_CATALOG = [
    {
        "key": "sales_report",
        "title": "Sales Report",
        "description": "Sales pipeline and revenue summary",
        "module": "sales",
        "generator": "build_sales_report",
        "search_placeholder": "Search owner, account or stage",
        "empty_message": "No sales records matched the selected filters.",
        "columns": [
            {"key": "owner", "label": "Owner"},
            {"key": "total_deals", "label": "Total Deals"},
            {"key": "open_deals", "label": "Open Deals"},
            {"key": "won_deals", "label": "Won Deals"},
            {"key": "pipeline_value", "label": "Pipeline Value"},
            {"key": "won_value", "label": "Won Value"},
        ],
    },
    {
        "key": "leads_report",
        "title": "Leads Report",
        "description": "Lead source, status and owner summary",
        "module": "sales",
        "generator": "build_leads_report",
        "search_placeholder": "Search lead, company, source or owner",
        "empty_message": "No leads matched the selected filters.",
        "columns": [
            {"key": "date_time", "label": "Date & Time"},
            {"key": "lead_name", "label": "Lead Name"},
            {"key": "company", "label": "Company"},
            {"key": "email", "label": "Email"},
            {"key": "phone", "label": "Phone"},
            {"key": "source", "label": "Source"},
            {"key": "owner", "label": "Owner"},
            {"key": "status", "label": "Status"},
            {"key": "score", "label": "Score"},
        ],
    },
    {
        "key": "contacts_report",
        "title": "Contacts Report",
        "description": "Contact growth, accounts and owner coverage",
        "module": "sales",
        "generator": "build_contacts_report",
        "search_placeholder": "Search contact, account, title or owner",
        "empty_message": "No contacts matched the selected filters.",
        "columns": [
            {"key": "created_at", "label": "Created"},
            {"key": "contact_name", "label": "Contact Name"},
            {"key": "account", "label": "Account"},
            {"key": "email", "label": "Email"},
            {"key": "phone", "label": "Phone"},
            {"key": "title", "label": "Title"},
            {"key": "owner", "label": "Owner"},
        ],
    },
    {
        "key": "deals_report",
        "title": "Deals Report",
        "description": "Pipeline, deal stage and closing visibility",
        "module": "sales",
        "generator": "build_deals_report",
        "search_placeholder": "Search deal, account, stage or owner",
        "empty_message": "No deals matched the selected filters.",
        "columns": [
            {"key": "created_at", "label": "Created"},
            {"key": "deal_name", "label": "Deal Name"},
            {"key": "account", "label": "Account"},
            {"key": "stage", "label": "Stage"},
            {"key": "amount", "label": "Amount"},
            {"key": "expected_revenue", "label": "Expected Revenue"},
            {"key": "owner", "label": "Owner"},
            {"key": "closing_date", "label": "Closing Date"},
        ],
    },
    {
        "key": "projects_report",
        "title": "Projects Report",
        "description": "Project progress, owners and delivery status",
        "module": "projects",
        "generator": "build_projects_report",
        "search_placeholder": "Search project, owner, status or account",
        "empty_message": "No projects matched the selected filters.",
        "columns": [
            {"key": "created_at", "label": "Created"},
            {"key": "project_code", "label": "Project Code"},
            {"key": "project_name", "label": "Project Name"},
            {"key": "account_name", "label": "Account"},
            {"key": "owner", "label": "Owner"},
            {"key": "status", "label": "Status"},
            {"key": "priority", "label": "Priority"},
            {"key": "progress", "label": "Progress"},
            {"key": "due_date", "label": "Due Date"},
        ],
    },
    {
        "key": "services_report",
        "title": "Services Report",
        "description": "Services catalog, pricing and delivery team summary",
        "module": "services",
        "generator": "build_services_report",
        "search_placeholder": "Search service, code, team or status",
        "empty_message": "No services matched the selected filters.",
        "columns": [
            {"key": "created_at", "label": "Created"},
            {"key": "service_code", "label": "Service Code"},
            {"key": "service_name", "label": "Service Name"},
            {"key": "status", "label": "Status"},
            {"key": "delivery_team", "label": "Delivery Team"},
            {"key": "price", "label": "Price"},
            {"key": "duration_minutes", "label": "Duration (min)"},
            {"key": "location_type", "label": "Location Type"},
            {"key": "created_by", "label": "Created By"},
        ],
    },
]

REPORT_CATALOG_BY_KEY = {report["key"]: report for report in REPORT_CATALOG}

REPORT_CATALOG_OPTIONS = [{"key": report["key"], "title": report["title"]} for report in REPORT_CATALOG]
