export const accountRelatedList = [
  "Notes",
  "Services",
  "Connected Records",
  "Attachments",
  "Deals",
  "Contacts",
  "Emails",
  "Open Activities",
  "Closed Activities",
  "Products",
  "Quotes",
  "Sales Orders",
  "Invoices",
  "Member Accounts",
  "Cases",
  "Solutions",
  "Social",
  "Links",
] as const;
