# Generated by Django 5.2.12 on 2026-03-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
