# Generated by Django 5.2.12 on 2026-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_campaign_alter_lead_id'),
    ]

    operations = []
